org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.2.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

create_version = 0.5.1.j-55
flywheel_version = 0.6.11-13
registrate_version = MC1.20-1.3.3
gamestages_version = 15.0.1
bookshelf_version = 20.1.6

# We keep the same mod id for compatiblity
mod_id=jackseconomy_legacy_create
mod_name=Jack's Economy (Forked): Legacy Create
mod_license=All-Rights-Reserved
# The version follows the format [JacksEconomyVersion]-[ForkVersion]
# JacksEconomyVersion is the version of Jack's Economy this version is built off
# ForkVersion is the version of this fork, which follows the format [MAJOR].[MINOR].[PATCH]
mod_version=1.2.2-1.3.3
mod_group_id=me.khajiitos
mod_authors=Khajiitos, Flapjack24, SCsupercraft
mod_description=Adds support for Create 0.5.f and above, and below Create 6.0\n\nBuilt into Jack's Economy (Forked)